### ISSUE TITLE
Toegankelijkheid: menuknop linksboven heeft geen naamgeving

### ISSUE THREAD

**Issue by demcat** [tthoeye/Citadel-Pois-Template#1]
Menuknop linksboven staat enkel gekend als een koppeling, heeft geen naamgeving (bezoeker heeft dus geen idee naar waar dit linkt of wat dit doet)

**Comment by tthoeye** [comment]
Het gebruik van het 'hamburger' icon om settings menu weer te geven lijkt me vrij goed ingeburgerd (zie onder). Behoeft dit echt nog een naamgeving of is dat niet wat je bedoelt? Misschien enkel op desktop versie dan?

![screen shot 2014-07-03 at 11 45 56](https://cloud.githubusercontent.com/assets/1484581/3467895/22a8f6f0-0297-11e4-9ca6-dd8022eba421.png)
![screen shot 2014-07-03 at 11 45 45](https://cloud.githubusercontent.com/assets/1484581/3467896/22ac11b4-0297-11e4-99a6-4d6b2405c466.png)
![screen shot 2014-07-03 at 11 44 35](https://cloud.githubusercontent.com/assets/1484581/3467897/22ade9f8-0297-11e4-9f4e-efbc9a1a8f3a.png)

**Comment by demcat** [comment]
Klopt! Het hamburger icoon is inderdaad tegenwoordig zeer goed ingeburgerd en dus geen probleem om dat zonder bewoording erbij te gebruiken.

Ik heb me niet duidelijk genoeg gemaakt vrees ik... Ik heb de site vooral getest naar gebruiksvriendelijkheid voor slechtzienden.
Als je met de tab-toets op het menu uitkomt en je maakt gebruik van een voorlees functie dan krijg je volgende te horen: "bezocht koppeling", waar je dus niet mee weet wat je zal openen (je weet niet dat dit een menu is). Het element op zich moet een naam krijgen zodat deze voorgelezen kan worden.

![schermafbeelding 2014-07-03 om 12 07 35](https://cloud.githubusercontent.com/assets/8003471/3468127/ed4b4e2e-0299-11e4-8291-e9e7844f891d.png)

Als je de tab verplaatst naar "in de buurt" dan werd het wel correct toegepast. Dan krijg je "Koppeling in de buurt lijst 3 onderdelen" (wat duidelijk maakt dat je op een koppeling zit van een lijst met 3 onderdelen: in de buurt, kaart, lijst). Koppeling maakt duidelijk dat je kan klikken en doet het systeem automatisch, maar je moet duidelijk maken waarop ze kunnen klikken.

![schermafbeelding 2014-07-03 om 12 10 56](https://cloud.githubusercontent.com/assets/8003471/3468158/68f2315a-029a-11e4-817a-1dc2740fcf57.png)

**Comment by tthoeye** [comment]
Thx! Dat is duidelijk :) 
Screenreader geinstalleerd (ChromeVox) en een naam toegevoegd aan de koppeling. Ik ben er nog niet uit hoe in kan aangeven hoeveel onderdelen er zich in het menu bevinden - wordt vervolgd.
