### ISSUE TITLE
Toegankelijkheid: filtermogelijkheden linksboven niet bruikbaar

### ISSUE THREAD

**Issue by demcat** [tthoeye/Citadel-Pois-Template#2]
Filtermogelijkheden linksboven kunnen ze ook niet gebruiken. Kunnen menu laten uitklappen maar de items in het menu kunnen ze niet instellen/toepassen

**Comment by tthoeye** [comment]
In het uitgeklapte filtermenu kunnen items normaal zichtbaar/onzichtbaar worden gemaakt, weliswaar na het klikken op 'toepassen'. Kan je aangeven welke browser/apparaat zodat ik het kan reproduceren?

**Comment by demcat** [comment]
werd uitgevoerd op macbook pro, chrome Versie 35.0.1916.153

**Comment by tthoeye** [comment]
Okay, het probleem was dat dit eigenlijk checkboxes zijn die werden verborgen. Na veeeel prutswerk hopelijk toch een oplossing gevonden :)

**Comment by demcat** [comment]
applausje voor jezelf! ;-) goe gedaan Thimo
